trigger:
  branches:
    include:
      - main  # ou 'dev', conforme o branch que usas

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'azureconnection' # <- nome da tua service connection
  azureFunctionApp: 'orders-processor-fn' # <- nome exato da Function App no portal
  functionProject: 'OrderFunction/OrderFunction.csproj' # <- caminho para o .csproj

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '$(functionProject)'

- task: DotNetCoreCLI@2
  displayName: 'Build function app'
  inputs:
    command: 'build'
    projects: '$(functionProject)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish function app'
  inputs:
    command: 'publish'
    projects: '$(functionProject)'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'functionApp'
    appName: '$(azureFunctionApp)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
