name: Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Azure Function
        run: dotnet publish ./OrderFunction/OrderFunction.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: orders-processor-fn
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
